# Directory where new environments are created
new_environments_directory: "/tmp/slopcoder-environments"

environments:
  - name: "MultiPL-E"
    directory: "/scratch/arjun-nosudo/repos/nuprl/MultiPL-E"
  - name: "slopcoder-test"
    directory: "/tmp/slopcoder-test"
